### ISSUE TITLE
Speed convert for mile_per_hour is incorrect

### ISSUE THREAD

**Issue by miriamccp** [HanSolo/converter#4]
the factor is incorrect, current is 0.4472271914, however, should be 0.44704
current:  
MILES_PER_HOUR(new Unit(Category.SPEED, "mph", "Miles per hour", new BigDecimal("0.4472271914")))
should be : MILES_PER_HOUR(new Unit(Category.SPEED, "mph", "Miles per hour", new BigDecimal("0.44704")))

**Comment by HanSolo** [comment]
Ups...my fault...thx for the heads-up, fixed it with commit ae4e83e3489a1c54bd540647a50ca504ed69a4ea
